### ISSUE TITLE
Parse error with ADTs

### ISSUE THREAD

**Issue by ErinvanderVeen** [nickel-lang/tree-sitter-nickel#45]
I was adding tests to Topiary for the new Nickel `or` keyword, but the example code doesn't parse. Here is a minimal working example (extracted from the Nickel `typecheck/or_patterns.ncl` test):

```nickel
f : forall a. [| 'Baz a |] -> Dyn
```

Removing the a resolves the parse issue:
```nickel
f : forall a. [| 'Baz |] -> Dyn
```

**Comment by yannham** [comment]
Ah, good catch. I think the pattern extension doesn't have anything to do with that, the grammar just hasn't been properly extended on the static type side. Because most of those appears in tests, and tests are currently not checked for formatting I believe, this might have slipped under the rug. Let me fix that quickly
